// L5, T12 is not used in unity

export type BoneMappingType = {
  prefix: string;
  bones: { [key: string]: string };
};
const BoneMapping: Record<string, BoneMappingType> = {
  mixamo: {
    prefix: 'mixamorig',
    bones: {
      Pelvis: 'Hips',
      L5: 'Spine',
      L3: 'Spine1',
      T12: 'Spine2',
      T8: 'Spine2',
      Neck: 'Neck',
      Head: 'Head',
      'Right Shoulder': 'RightShoulder',
      'Right Upper Arm': 'RightArm',
      'Right Forearm': 'RightForeArm',
      'Right Hand': 'RightHand',
      'Left Shoulder': 'LeftShoulder',
      'Left Upper Arm': 'LeftArm',
      'Left Forearm': 'LeftForeArm',
      'Left Hand': 'LeftHand',
      'Right Upper Leg': 'RightUpLeg',
      'Right Lower Leg': 'RightLeg',
      'Right Foot': 'RightFoot',
      'Right Toe': 'RightToeBase',
      'Left Upper Leg': 'LeftUpLeg',
      'Left Lower Leg': 'LeftLeg',
      'Left Foot': 'LeftFoot',
      'Left Toe': 'LeftToeBase',
      'Left Carpus': 'LeftHand',
      'Left First Metacarpal': 'LeftHandThumb1',
      'Left First Proximal Phalange': 'LeftHandThumb2',
      'Left First Distal Phalange': 'LeftHandThumb3',
      'Left Second Metacarpal': 'LeftHandIndex1',
      'Left Second Proximal Phalange': 'LeftHandIndex1',
      'Left Second Middle Phalange': 'LeftHandIndex2',
      'Left Second Distal Phalange': 'LeftHandIndex3',
      'Left Third Metacarpal': 'LeftHandMiddle1',
      'Left Third Proximal Phalange': 'LeftHandMiddle1',
      'Left Third Middle Phalange': 'LeftHandMiddle2',
      'Left Third Distal Phalange': 'LeftHandMiddle3',
      'Left Fourth Metacarpal': 'LeftHandRing1',
      'Left Fourth Proximal Phalange': 'LeftHandRing1',
      'Left Fourth Middle Phalange': 'LeftHandRing2',
      'Left Fourth Distal Phalange': 'LeftHandRing3',
      'Left Fifth Metacarpal': 'LeftHandPinky1',
      'Left Fifth Proximal Phalange': 'LeftHandPinky1',
      'Left Fifth Middle Phalange': 'LeftHandPinky2',
      'Left Fifth Distal Phalange': 'LeftHandPinky3',
      'Right Carpus': 'RightHand',
      'Right First Metacarpal': 'RightHandThumb1',
      'Right First Proximal Phalange': 'RightHandThumb2',
      'Right First Distal Phalange': 'RightHandThumb3',
      'Right Second Metacarpal': 'RightHandIndex1',
      'Right Second Proximal Phalange': 'RightHandIndex1',
      'Right Second Middle Phalange': 'RightHandIndex2',
      'Right Second Distal Phalange': 'RightHandIndex3',
      'Right Third Metacarpal': 'RightHandMiddle1',
      'Right Third Proximal Phalange': 'RightHandMiddle1',
      'Right Third Middle Phalange': 'RightHandMiddle2',
      'Right Third Distal Phalange': 'RightHandMiddle3',
      'Right Fourth Metacarpal': 'RightHandRing1',
      'Right Fourth Proximal Phalange': 'RightHandRing1',
      'Right Fourth Middle Phalange': 'RightHandRing2',
      'Right Fourth Distal Phalange': 'RightHandRing3',
      'Right Fifth Metacarpal': 'RightHandPinky1',
      'Right Fifth Proximal Phalange': 'RightHandPinky1',
      'Right Fifth Middle Phalange': 'RightHandPinky2',
      'Right Fifth Distal Phalange': 'RightHandPinky3',
    },
  },
};

export default BoneMapping;
